mariusbegby/cadence-discord-bot

.github/workflows/node.js.yml

Created CI workflow for Node.js.
Will make sure project can be installed with dependencies on supported Node.js versions.

Add Node.js CI workflow

---

.github/workflows/node.js.yml
.github/workflows/release-please.yml

Add release please action workflow

Add release please action workflow

---

.github/workflows/release-please.yml

Create pr with release notes in workflow

Create pr with release notes

---

.github/workflows/release-please.yml

Add token to action workflow

---

commands/filters.js
commands/leave.js
commands/pause.js
commands/play.js
commands/queue.js
commands/remove.js
commands/skip.js
commands/volume.js

Update interaction editReply

---

package.json

Update package.json with license and other metadata

Update package.json with license and other metadata

---

commands/skip.js

fix: formatting

---

README.md

README.md badge changes

---

.github/workflows/release-please.yml

fix: Update command in workflow

fix: Update command in workflow

---

README.md
commands/skip.js
index.js
system-commands/guilds.js

Updated README + fixed link to MIT license.
Stop sending warning message for `/filters` if execution time is over 55 seconds - times out at 60 seconds of no interaction, and this is expected.
Limit `/guilds` system command character length to 4000. Discord has a 4096 character limit on messages.
Solved edge case trying to read title from current track in queue when there is none for `/skip` command.

Bug fixes and changes

---

package-lock.json
package.json

Update version number to v1.0.1

Update version number to v1.0.1

---

.github/workflows/release-please.yml

Release action workflow command update

Release action workflow command update

---

.github/workflows/release-please.yml

fix: Remove release-please command in workflow

fix: Remove release-please command in workflow

---

commands/filters.js
commands/pause.js
commands/play.js
commands/queue.js
commands/remove.js
commands/skip.js
commands/volume.js
index.js
package-lock.json
package.json

- Add support for adding playlists in `/play` command.
- Updated `@discord-player/extractor` from `4.3.1` to `4.4.0`.
- Updated `discord-player` from `6.6.0` to `6.6.1`.
- Add `onBeforeCreateStream()` hook to reduce issues with long duration YouTube videos.
- Changed library from `play-dl` to `yt-stream`, which should be a bit faster.
- Various changes to reply message format/content.
- Set max queue size to 10,000 and max history from queue to 100.

Fixes and playlist support

---

.gitignore
commands/filters.js
config.json.example
deploy-commands.js
deploy-system-commands.js
index.js
package-lock.json
package.json
services/logger.js

- Added logging library pino.
- Added pino-pretty for formatting of logging to console.
- Setup logging to console and files based on log level.
- Added configurable options for log leve.
- Updated config.json.example with example log level configuration.
- Replaced console.log() statements with new logger.
- Logging messages along with related object can now be done in one statement.
- Smaller formatting changes.

Add pino logging library

---

commands/help.js
commands/pause.js
commands/play.js
commands/queue.js
commands/remove.js
commands/skip.js

- Updated descriptions for commands, also in the `/help` command.

fix: Updated descriptions for commands and /help command

---

commands/filters.js
commands/help.js
commands/play.js
config.json.example
index.js

- Added configurable symbols/icons/emojis for user replies.
- Added configurable options for bot info, such as support server invite url.
No changes.

fix: Added more configurable options for user replies

---

commands/filters.js
commands/help.js
commands/leave.js
commands/nowplaying.js
commands/pause.js
commands/play.js
commands/queue.js
commands/remove.js
commands/skip.js
commands/volume.js
config.json.example
index.js
system-commands/guilds.js
system-commands/status.js

- Overhauled all messages sent back to user.
- Added configurable icons to be used in embed messages.
- Make sure interaction replies are in consistent format back to user (same color for same events, same style, etc.).
- Added more handling of errors in `/play` command.
- Other various small fixes and improvements.
No changes.

Improved user messages

---

commands/filters.js
commands/leave.js
commands/nowplaying.js
commands/pause.js
commands/play.js
commands/remove.js
commands/skip.js
commands/volume.js

- Show user nickname in interaction reply if set instead of username
No changes.

fix: Show user nickname in interaction reply if set instead of username

---

commands/nowplaying.js

- Fix retrieving play count from track. If track.views is 0, try to retrieve from track.metadata.bridge.views instead.
No changes.

Play count from track

---

commands/nowplaying.js
commands/remove.js
commands/skip.js

- Fix error when trying to access track.metadata.bridge.views when track.metadata.bridge is not set.
- Removed period after link to source in messages.
No changes.

Small changes

---

commands/loop.js

- Fixed typo in /loop command description
No changes.

fix: fixed typo in /loop command description

---

commands/filters.js
commands/help.js
commands/leave.js
commands/loop.js
commands/nowplaying.js
commands/pause.js
commands/play.js
commands/queue.js
commands/remove.js
commands/seek.js
commands/skip.js
commands/volume.js
system-commands/guilds.js

- Added `/seek` command with input validation for correct duration format.
- Update duration format to show with bold text in places where shown.
- Update commands to show with bold text when referenced in replies.
- Updated `/help` command with updated info.
- Fixed system command `/guilds` heading text.
No changes.

Seek command

---

commands/nowplaying.js
commands/queue.js
config.json.example
index.js

- Show icon for track source in `/nowplaying`.
- More debug logging.
- Other small fixes.
No changes.

Show icon for track source

---

.gitignore
package.json
src/commands/filters.js
src/commands/help.js
src/commands/leave.js
src/commands/loop.js
src/commands/nowplaying.js
src/commands/pause.js
src/commands/play.js
src/commands/queue.js
src/commands/remove.js
src/commands/seek.js
src/commands/skip.js
src/commands/volume.js
src/deploy-commands.js
src/deploy-system-commands.js
src/index.js
src/services/logger.js
src/system-commands/guilds.js
src/system-commands/status.js

- Moved source files into `/src` folder.
- Logger will now write logs to `/logs/app-x.log` instead of in root directory.
No changes.

feat!: Moved source into /src folder

---

src/commands/player/filters.js
src/commands/player/leave.js
src/commands/player/loop.js
src/commands/player/nowplaying.js
src/commands/player/pause.js
src/commands/player/play.js
src/commands/player/queue.js
src/commands/player/remove.js
src/commands/player/seek.js
src/commands/player/skip.js
src/commands/player/volume.js
src/commands/system/guilds.js
src/commands/system/status.js
src/utils/validation/queueValidation.js
src/utils/validation/systemCommandValidation.js
src/utils/validation/voiceChannelValidation.js

- Extracted common logic for validation of command execution, e.g. to check if user is in voice channel, queue is empty, etc.
No changes.

feat: Added common logic for validating command execution

---

src/events/client/ready.js
src/index.js
src/utils/factory/createClient.js
src/utils/factory/createPlayer.js
src/utils/other/postBotStats.js

- Moved some utility functions into separate folders
No changes.

fix: Moved some utility into categorized folders

---

src/commands/player/nowplaying.js
src/commands/player/play.js
src/utils/validation/searchQueryValidation.js

- Added search query validator, currently only to transform Spotify URLs.
- Fix country-based Spotify URLs not showing search result due to unexpected URL format with additional path.
- Updated text in `/nowplaying` from Audio source to Track source. It is more accurate since the audio is actually from YouTube through the bridgeprovider.
- No changes.

Some changes

---

src/commands/player/filters.js
src/commands/player/leave.js
src/commands/player/loop.js
src/commands/player/nowplaying.js
src/commands/player/pause.js
src/commands/player/play.js
src/commands/player/queue.js
src/commands/player/remove.js
src/commands/player/seek.js
src/commands/player/skip.js
src/commands/player/volume.js
src/utils/validation/queueValidation.js
src/utils/validation/searchQueryValidation.js
src/utils/validation/voiceChannelValidation.js

- Add more debug logging to all commands.
No changes.

Logging in commands

---

src/utils/deploySlashCommands.js
src/utils/registerClientCommands.js
src/utils/registerEventListeners.js

- Fixed requiring local files.
No changes.

fix: fix requiring local files

---

src/events/player/playerStart.js
src/utils/registerEventListeners.js

- Small changes to logging
No changes.

fix: small changes to logging

---

README.md
src/services/logger.js

- Updated logging to separate levels.
- Updated README.md.
No changes.

Some improvements

---

.env.example
README.md
package-lock.json
package.json
src/utils/deploySlashCommands.js
src/utils/factory/createClient.js
src/utils/factory/createPlayer.js
src/utils/registerClientCommands.js

- Small code optimizations.
- Change YouTube cookie name from YOUTUBE_COOKIE to YT_COOKIE to ensure support for `yt-stream` to use it.
- Added setup instructions for `pm2`.
- Some more error handling and logging to util functions.
Updated mediaplex and discord-player extractor to new development versions.

Changes and stuff

---

src/commands/player/play.js

- Handle more youtube warning messages/confirmations when trying to extract audio.
No changes.

Handle youtube warnings

---

src/commands/info/status.js
src/commands/system/systemstatus.js
src/config_example.js
src/utils/factory/createPlayer.js
src/utils/system/getUptimeFormatted.js

- Changed /status command to be a user command. Updated information and design to be user-friendly.
- Changed old /status command to be new /systemstatus command, has same info as the user-friendly /status command, but with additional technical information.
- Added two new icons in config.js for displaying Discord icon and Server icon, used in /status command.
- /status commands can now show information about active voice connections, total tracks in queue and total listeners, working with sharding.
No changes.

User status command

---

src/commands/player/play.js
src/config_example.js

- Added configurable options for buffering and connection timeout
No changes.

fix: Added configurable options for buffering and connection timeout

---

src/commands/player/play.js
src/config_example.js
src/events/interactions/interactionCreate.js

- Handle max queue size in /play command when adding large playlists.
No changes.

fix: Handle max queue size in /play command when adding large playlists.

---

src/commands/player/filters.js
src/commands/player/nowplaying.js
src/events/interactions/interactionCreate.js

- Extend collector filter on interactions from message components to 300 seconds for now.
- No longer warn users about execution time, only send to logger.
- No longer check for permissions on interactions unless it's a chat input command (to avoid errors on autocomplete etc.).
No changes.

evening improvements :)

---

src/events/interactions/interactionCreate.js

- Possibly fix interaction not reply errors by checking if interaction is replied or not before followUp.
No changes.

fix: Possibly fix interaction not reply errors

---

src/commands/player/play.js
src/events/interactions/interactionCreate.js

- Additional handling of autocomplete interaction errors
No changes.

fix: Additional handling of autocomplete interaction errors

---

src/commands/player/play.js

- Handle "all" yt warnings requiring confirmations.
No changes.

fix: handle "all" yt warnings requiring confirmations

---

src/commands/player/play.js

- Fixed error when no thumbnail available
No changes.

fix: Fixed error when no thumbnail available

---

src/bot.js
src/commands/system/reload.js
src/utils/registerClientCommands.js

- Added reload command
No changes.

feat: Added reload command

---

src/commands/info/help.js
src/commands/player/filters.js
src/commands/player/leave.js
src/commands/player/loop.js
src/commands/player/lyrics.js
src/commands/player/nowplaying.js
src/commands/player/pause.js
src/commands/player/play.js
src/commands/player/queue.js
src/commands/player/remove.js
src/commands/player/seek.js
src/commands/player/shuffle.js
src/commands/player/skip.js
src/commands/player/stop.js
src/commands/player/volume.js
src/utils/validation/voiceChannelValidator.js

- Added new /lyrics command.
- Added new /reload system command.
- Validate if user is in same voice channel as bot.
- Other small changes.
No changes.

Lyrics command

---

package-lock.json
package.json

- Updated dependencies
No changes.

fix: Updated dependencies

---

.github/workflows/contributors.yml

- add workflow for auto adding contributors to readme
No changes.

chore: add workflow for auto adding contributors to readme

---

package-lock.json
package.json
src/commands/player/play.js
src/utils/factory/createPlayer.js

- Change from yt-stream to @distube/ytdl-core for streaming audio
- Removed yt-stream as dependency, added @distube/ytdl-core.

feat: Change from yt-stream to @distube/ytdl-core for streaming audio

---

src/events/interactions/interactionCreate.js

Interaction duplicate test

---

src/events/interactions/interactionCreate.js
src/utils/validation/permissionValidator.js

- adjustments to error and permission handling
No changes

fix: adjustments to error and permission handling

---

Dockerfile

Updated Dockerfile to support new config file name/location, will now build regardless of `local.js` existence in build directory. Updated `--legacy-peer-deps` to `--production` per our previous discussion.
N/A

Updated Dockerfile to new config

---

src/commands/system/shards.js
src/commands/system/systemstatus.js

- Add /shards system command
No change.

V4 improvements

---

.github/workflows/bun.yml
.github/workflows/node.js.yml

Add Bun CI workflow
No changes.

chore: Add Bun CI workflow

---

.github/workflows/bun.yml
.github/workflows/node.js.yml
.gitignore
config/test.js
package-lock.json
package.json
src/tests/validation.test.ts

- Added setup for unit tests. Created a few unit tests.
- Added `jest`, `ts-jest` and `@types/jest` to devDependencies.

fix: Added setup for unit tests

---

src/tests/validation.test.ts

remove comment

---

src/bot.ts

- await client.login, spotted thanks to @Kriblin
- No changes

fix: await client.login, thanks to @Kriblin

---

src/classes/interactions.ts
src/interactions/commands/player/history.ts
src/types/utilTypes.d.ts
src/utils/validation/queueValidator.ts

- Add new `/history` command to show previously played tracks
- No changes

feat: Add new /history command to show previously played tracks

---

src/interactions/commands/player/back.ts
src/interactions/commands/player/skip.ts

- Added /back command to go back in history
No changes

feat: Added /back command to go back in history

---

src/interactions/commands/player/queue.ts
src/interactions/components/nowplaying-back-button.ts
src/interactions/components/nowplaying-playpause-button.ts

Adds buttons to the queue command. Skip/Back doesn't show up if it's not possible to execute the action.

Queue command buttons (#241)

---

src/interactions/commands/player/history.ts
src/interactions/commands/player/nowplaying.ts
src/interactions/commands/player/queue.ts
src/interactions/components/action-pauseresume-button.ts
src/interactions/components/action-previous-button.ts
src/interactions/components/action-skip-button.ts

- Updated new action components for /queue command by @tacheometry
- Added new action components to /history and /nowplaying
No changes.

Updated action components

---

src/interactions/commands/player/back.ts
src/interactions/commands/player/remove.ts
src/interactions/commands/player/skip.ts

- Updated /remove command to support: range, queue, user and duplicates!
- Changed naming of `trackNumber` to `position` various places to make it more consistent.
- No changes

Remove command updates

---

locales/en/bot.json
locales/no/bot.json
locales/ro/bot.json
src/interactions/commands/player/seek.ts

Romanian translation

---

.gitignore
package-lock.json
package.json
prisma/schema.prisma
src/index.ts
src/services/guildDatabaseService.ts
src/services/prismaClient.ts

- Implement Prisma for persistent storage
- Just boilerplate code to get started. Service will be expanded with more exposed methods and then these methods will be implemented into commands so users can do CRUD operations to change default volume, set locale etc. etc.
- Added @prisma/client to dependencies

feat!: Implement Prisma for persistent storage

---

locales/en/bot.json
locales/es-ES/bot.json
prisma/schema.prisma
src/common/services/guildDatabaseClient.ts
src/interactions/slashcommands/settings.ts

- implemented settings command
- changed some locales strings from spanish translation

feat(settings): Implement settings command
